### ISSUE TITLE
Jupyter Notebooks examples and tutorials to not work with docker-compose

### ISSUE THREAD

**Issue by KadKla** [OpenMined/PyGrid#543]
**Describe the bug**
I launched the gateway and nodes with the provided docker-compose and tried to connect with a local running JupyterLab as well as with a JupyterLab running inside the docker-compose. In Both cases I cannot execute successfully the examples from two different examples:  [pygrid in pysyft](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/grid) (here Part 1 worked and the nodes seem to know each other) nor the [pygrid examples](https://github.com/OpenMined/PyGrid/tree/dev/examples)

I changed optionally localhost to gateway, alice, bob, etc., however, this did not change anything. Before I launched the docker-compose I added all the hosts to the /etc/hosts file:

```
127.0.0.1       gateway
127.0.0.1       bob
127.0.0.1       alice
127.0.0.1       bill
127.0.0.1       james
```

In the local as well as in the jupyterlab running in the docker-container I get the following error:

```
Websocket connection closed (worker: Bob)
Created new websocket connection
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-12b0ebb6e5f3> in <module>
      7 and storing a pointer plan that manages all remote references.
      8 '''
----> 9 cloud_grid_service.serve_model(model,id=model.id,allow_remote_inference=True, mpc=True) # If mpc flag is False, It will host a unencrypted model.

/opt/conda/lib/python3.7/site-packages/syft/grid/public_grid.py in serve_model(self, model, id, mpc, allow_remote_inference, allow_download, n_replica)
     64             self._serve_unencrypted_model(model, id, allow_remote_inference, allow_download)
     65         else:
---> 66             self._serve_encrypted_model(model)
     67 
     68     def query_model_hosts(

/opt/conda/lib/python3.7/site-packages/syft/grid/public_grid.py in _serve_encrypted_model(self, model)
    162 
    163                     # SMPC Share
--> 164                     model.fix_precision().share(*smpc_workers, crypto_provider=crypto_provider)
    165 
    166                     # Host model

/opt/conda/lib/python3.7/site-packages/syft/execution/plan.py in share_(self, *args, **kwargs)
    526 
    527     def share_(self, *args, **kwargs):
--> 528         self.state.share_(*args, **kwargs)
    529         return self
    530 

/opt/conda/lib/python3.7/site-packages/syft/execution/state.py in share_(self, *args, **kwargs)
    100         for tensor in self.tensors():
    101             self.create_grad_if_missing(tensor)
--> 102             tensor.share_(*args, **kwargs)
    103 
    104     def get_(self):

/opt/conda/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in share_(self, *args, **kwargs)
    896                 kwargs["requires_grad"] = False
    897 
--> 898             shared_tensor = self.child.share_(*args, **kwargs)
    899 
    900             if requires_grad and not isinstance(shared_tensor, syft.PointerTensor):

/opt/conda/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/precision.py in share_(self, *args, **kwargs)
    929         contrary to the classic share version version
    930         """
--> 931         self.child = self.child.share_(*args, no_wrap=True, **kwargs)
    932         return self
    933 

/opt/conda/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in share_(self, *args, **kwargs)
    904             return self
    905         else:
--> 906             return self.share(*args, **kwargs)  # TODO change to inplace
    907 
    908     def combine(self, *pointers):

/opt/conda/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in share(self, field, crypto_provider, requires_grad, no_wrap, *owners)
    875                 )
    876                 .on(self.copy(), wrap=False)
--> 877                 .init_shares(*owners)
    878             )
    879 

/opt/conda/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/additive_shared.py in init_shares(self, *owners)
    198         shares_dict = {}
    199         for share, owner in zip(shares, owners):
--> 200             share_ptr = share.send(owner, **no_wrap)
    201             shares_dict[share_ptr.location.id] = share_ptr
    202 

/opt/conda/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in send(self, inplace, user, local_autograd, preinitialize_grad, no_wrap, garbage_collect_data, *location)
    417                 local_autograd=local_autograd,
    418                 preinitialize_grad=preinitialize_grad,
--> 419                 garbage_collect_data=garbage_collect_data,
    420             )
    421 

/opt/conda/lib/python3.7/site-packages/syft/workers/base.py in send(self, obj, workers, ptr_id, garbage_collect_data, create_pointer, **kwargs)
    385 
    386         # Send the object
--> 387         self.send_obj(obj, worker)
    388 
    389         # If we don't need to create the pointer

/opt/conda/lib/python3.7/site-packages/syft/workers/base.py in send_obj(self, obj, location)
    678                 receive the object.
    679         """
--> 680         return self.send_msg(ObjectMessage(obj), location)
    681 
    682     def request_obj(

/opt/conda/lib/python3.7/site-packages/syft/workers/base.py in send_msg(self, message, location)
    285 
    286         # Step 2: send the message and wait for a response
--> 287         bin_response = self._send_msg(bin_message, location)
    288 
    289         # Step 3: deserialize the response

/opt/conda/lib/python3.7/site-packages/syft/workers/virtual.py in _send_msg(self, message, location)
     13             sleep(self.message_pending_time)
     14 
---> 15         return location._recv_msg(message)
     16 
     17     def _recv_msg(self, message: bin) -> bin:

/opt/conda/lib/python3.7/site-packages/syft/workers/websocket_client.py in _recv_msg(self, message)
    103             if not self.ws.connected:
    104                 raise RuntimeError(
--> 105                     "Websocket connection closed and creation of new connection failed."
    106                 )
    107         return response

RuntimeError: Websocket connection closed and creation of new connection failed.
```

In the docker-compose look I get the following, however, not sure if the error occurs at the same time:

```
bob_1      | Traceback (most recent call last):
bob_1      |   File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
bob_1      |     self.run_application()
bob_1      |   File "/usr/local/lib/python3.7/site-packages/geventwebsocket/handler.py", line 75, in run_application
bob_1      |     self.run_websocket()
bob_1      |   File "/usr/local/lib/python3.7/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
bob_1      |     list(self.application(self.environ, lambda s, h, e=None: []))
bob_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
bob_1      |     return self.wsgi_app(environ, start_response)
bob_1      |   File "/usr/local/lib/python3.7/site-packages/flask_sockets.py", line 45, in __call__
bob_1      |     handler(environment, **values)
bob_1      |   File "/app/app/main/events/__init__.py", line 57, in socket_api
bob_1      |     response = route_requests(message)
bob_1      |   File "/app/app/main/events/__init__.py", line 37, in route_requests
bob_1      |     return forward_binary_message(message)
bob_1      |   File "/app/app/main/auth/__init__.py", line 60, in wrapped
bob_1      |     return f(*args, **kwargs)
bob_1      |   File "/app/app/main/events/syft_events.py", line 27, in forward_binary_message
bob_1      |     decoded_response = current_user.worker._recv_msg(message)
bob_1      |   File "/usr/local/lib/python3.7/site-packages/syft/workers/virtual.py", line 19, in _recv_msg
bob_1      |     return self.recv_msg(message)
bob_1      |   File "/usr/local/lib/python3.7/site-packages/syft/workers/base.py", line 314, in recv_msg
bob_1      |     msg = sy.serde.deserialize(bin_message, worker=self)
bob_1      |   File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 69, in deserialize
bob_1      |     return strategy(binary, worker)
bob_1      |   File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 381, in deserialize
bob_1      |     return _deserialize_msgpack_simple(simple_objects, worker)
bob_1      |   File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 372, in _deserialize_msgpack_simple
bob_1      |     return _detail(worker, simple_objects)
bob_1      |   File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 472, in _detail
bob_1      |     return detailers[obj[0]](worker, obj[1], **kwargs)
bob_1      |   File "/usr/local/lib/python3.7/site-packages/syft/messaging/message.py", line 252, in detail
bob_1      |     return ObjectMessage(sy.serde.msgpack.serde._detail(worker, msg_tuple[0]))
bob_1      |   File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 472, in _detail
bob_1      |     return detailers[obj[0]](worker, obj[1], **kwargs)
bob_1      |   File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/torch_serde.py", line 192, in _detail_torch_tensor
bob_1      |     ) = tensor_tuple
bob_1      | ValueError: not enough values to unpack (expected 9, got 7)
bob_1      | 2020-04-18T16:19:18Z {'REMOTE_ADDR': '172.22.0.8', 'REMOTE_PORT': '60776', 'HTTP_HOST': 'bob:3000', (hidden keys: 26)} failed with ValueError
```
Here is the docker-compose file I used:
```
version: '3'
services:
    gateway:
        image: openmined/grid-gateway:latest
        build: .
        environment:
            - PORT=5000
            - SECRET_KEY=ineedtoputasecrethere
            - DATABASE_URL=sqlite:///databasegateway.db
        ports:
        - 5000:5000
    redis:
        image: redis:latest
        volumes:
            - ./redis-data:/data
        expose:
        - 6379
        ports:
        - 6379:6379
    jupyter:
        image: openmined/pysyft-notebook
        environment:
            - WORKSPACE_DIR=/root
        volumes:
            - .:/root
        depends_on:
            - "gateway"
            - "redis"
            - "bob"
            - "alice"
            - "bill"
            - "james"
        entrypoint: ["jupyter", "notebook", "--allow-root", "--ip=0.0.0.0", "--port=8888", "--notebook-dir=/root"]
        expose:
        - 8888
        ports:
        - 8888:8888
    bob:
        image: openmined/grid-node:latest
        environment:
            - GRID_NETWORK_URL=http://gateway:5000
            - ID=Bob
            - ADDRESS=http://bob:3000/
            - REDISCLOUD_URL=redis://redis:6379
            - PORT=3000
        depends_on:
            - "gateway"
            - "redis"
        expose:
            - 3000
        ports:
        - 3000:3000
    alice:
        image: openmined/grid-node:latest
        environment:
            - GRID_NETWORK_URL=http://gateway:5000
            - ID=Alice
            - ADDRESS=http://alice:3001/
            - REDISCLOUD_URL=redis://redis:6379
            - PORT=3001
        depends_on:
            - "gateway"
            - "redis"
        expose:
            - 3001
        ports:
        - 3001:3001
    bill:
        image: openmined/grid-node:latest
        environment:
            - GRID_NETWORK_URL=http://gateway:5000
            - ID=Bill
            - ADDRESS=http://bill:3002/
            - REDISCLOUD_URL=redis://redis:6379
            - PORT=3002
        depends_on:
            - "gateway"
            - "redis"
        expose:
            - 3002
        ports:
        - 3002:3002
    james:
        image: openmined/grid-node:latest
        environment:
            - GRID_NETWORK_URL=http://gateway:5000
            - ID=James
            - ADDRESS=http://james:3003/
            - REDISCLOUD_URL=redis://redis:6379
            - PORT=3003
        depends_on:
            - "gateway"
            - "redis"
        expose:
            - 3003
        ports:
        - 3003:3003
```

**To Reproduce**
1. Run the docker-compose file
2. Launch a JupyterLab-notebook locally
3. Test the different tutorials

**Expected behavior**
Successful execution of the jupyter notebooks

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
In the future we want to transfer the whole docker-compose setup to Kubernetes
