### ISSUE TITLE
Problems setting up a PyGrid across devices

### ISSUE THREAD

**Issue by Benecoder** [OpenMined/PyGrid#565]
**Describe the bug**
I want to set up a PyGrid with the Gateway running on one node and the worker on a seperate instance. The worker continuously times out.
```
bob_1    | [2020-05-14 16:01:53 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
bob_1    | [2020-05-14 16:01:53 +0000] [10] [INFO] Worker exiting (pid: 10)
```

**To Reproduce**
Both the gateway and the worker have docker and docker compose installed.

The Gateway is started using:
```
sudo docker pull openmined/grid-gateway
sudo docker-compose up 
```

where the **docker-compose.yml** file is 
```
version: '3'
services:
    gateway:
        image: openmined/grid-gateway:latest
        build: .
        environment:
                - PORT=5000
                - SECRET_KEY=ineedtoputasecrethere
                - DATABASE_URL=sqlite:///databasegateway.db
        ports:
        - 5000:5000
    redis:
        image: redis:latest
        expose:
        - 6379
        ports:
        - 6379:6379
```

The worker is started using 
```
sudo docker pull openmined/grid-node
sudo docker-compose up 
```
where the docker-compose.yml file is:
```
version: '3'
services:
    redis:
        image: redis:latest
        expose:
        - 6379
        ports:
        - 6379:6379
    bob:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://<ip-of-the-gateway>:5000
                - ID=Bob
                - ADDRESS=http://<ip-of-the-worker>:3000/
                - PORT=3000
        depends_on:
                - "redis"
        ports:
        - 3000:3000
```

**Expected behavior**
The workers connect to the gateway.

The full error message of the workers is:

```
Creating network "ubuntu_default" with the default driver
Pulling redis (redis:latest)...
latest: Pulling from library/redis
54fec2fa59d0: Already exists
9c94e11103d9: Pull complete
04ab1bfc453f: Pull complete
a22fde870392: Pull complete
def16cac9f02: Pull complete
1604f5999542: Pull complete
Digest: sha256:584db7c588cd6d1e0a97bcf67c49016d4f19320b614e07049404bea1d681965e
Status: Downloaded newer image for redis:latest
Creating ubuntu_redis_1 ... done
Creating ubuntu_bob_1   ... done
Attaching to ubuntu_redis_1, ubuntu_bob_1
redis_1  | 1:C 14 May 2020 16:01:17.715 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 14 May 2020 16:01:17.715 # Redis version=6.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 14 May 2020 16:01:17.715 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 14 May 2020 16:01:17.717 * Running mode=standalone, port=6379.
redis_1  | 1:M 14 May 2020 16:01:17.717 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1  | 1:M 14 May 2020 16:01:17.717 # Server initialized
redis_1  | 1:M 14 May 2020 16:01:17.717 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 14 May 2020 16:01:17.717 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1  | 1:M 14 May 2020 16:01:17.718 * Ready to accept connections
bob_1    | [2020-05-14 16:01:23 +0000] [1] [INFO] Starting gunicorn 19.9.0
bob_1    | [2020-05-14 16:01:23 +0000] [1] [INFO] Listening at: http://0.0.0.0:3000 (1)
bob_1    | [2020-05-14 16:01:23 +0000] [1] [INFO] Using worker: flask_sockets.worker
bob_1    | [2020-05-14 16:01:23 +0000] [10] [INFO] Booting worker with pid: 10
bob_1    | [2020-05-14 16:01:53 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
bob_1    | [2020-05-14 16:01:53 +0000] [10] [INFO] Worker exiting (pid: 10)
bob_1    | [2020-05-14 16:01:53 +0000] [12] [INFO] Booting worker with pid: 12

```

**Desktop (please complete the following information):**
 - OS: ubuntu 18
 - openmined/grid-node container 50904dc383de
 - openmined/grid-gateway container 2157d1e2291c
